import type { EnrichedUserCrumb } from '@api/modules/crumbs/crumbs.types';
import {
  DEFAULT_NYC_COORDINATES,
  USER_NEIGHBORHOOD_ZOOM_DELTA,
  type MapCoordinates,
  type MapRegion,
} from '@/types/map';

/**
 * GeoJSON Point Feature containing an EnrichedUserCrumb
 */
export interface CrumbPointFeature {
  type: 'Feature';
  properties: {
    cluster: false;
    crumb: EnrichedUserCrumb;
    crumbId: string;
  };
  geometry: {
    type: 'Point';
    coordinates: [number, number]; // [longitude, latitude]
  };
}

/**
 * GeoJSON Cluster Feature generated by spatial grid clustering
 */
export interface CrumbClusterFeature {
  type: 'Feature';
  properties: {
    cluster: true;
    cluster_id: string;
    point_count: number;
    crumbs: EnrichedUserCrumb[];
  };
  geometry: {
    type: 'Point';
    coordinates: [number, number]; // [longitude, latitude]
  };
}

export type CrumbMapClusterItem = CrumbPointFeature | CrumbClusterFeature;

/**
 * Haversine formula for distance calculation between two lat/lng coordinates in miles.
 */
export function haversineDistanceMiles(
  lat1: number,
  lon1: number,
  lat2: number,
  lon2: number,
): number {
  const toRad = (deg: number) => (deg * Math.PI) / 180;
  const R = 3958.8; // Earth's radius in miles

  const dLat = toRad(lat2 - lat1);
  const dLon = toRad(lon2 - lon1);

  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(toRad(lat1)) *
      Math.cos(toRad(lat2)) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);

  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

/**
 * Calculates a MapRegion bounding box encompassing all supplied coordinates with padding.
 */
export function getBoundingRegionForCoordinates(
  coordinates: MapCoordinates[],
  paddingFactor = 1.35,
): MapRegion {
  if (coordinates.length === 0) {
    return DEFAULT_NYC_COORDINATES;
  }

  if (coordinates.length === 1) {
    return {
      latitude: coordinates[0].latitude,
      longitude: coordinates[0].longitude,
      latitudeDelta: USER_NEIGHBORHOOD_ZOOM_DELTA.latitudeDelta,
      longitudeDelta: USER_NEIGHBORHOOD_ZOOM_DELTA.longitudeDelta,
    };
  }

  let minLat = coordinates[0].latitude;
  let maxLat = coordinates[0].latitude;
  let minLng = coordinates[0].longitude;
  let maxLng = coordinates[0].longitude;

  for (let i = 1; i < coordinates.length; i++) {
    const c = coordinates[i];
    if (c.latitude < minLat) minLat = c.latitude;
    if (c.latitude > maxLat) maxLat = c.latitude;
    if (c.longitude < minLng) minLng = c.longitude;
    if (c.longitude > maxLng) maxLng = c.longitude;
  }

  const centerLat = (minLat + maxLat) / 2;
  const centerLng = (minLng + maxLng) / 2;
  const latDelta = Math.max((maxLat - minLat) * paddingFactor, 0.012);
  const lngDelta = Math.max((maxLng - minLng) * paddingFactor, 0.012);

  return {
    latitude: centerLat,
    longitude: centerLng,
    latitudeDelta: latDelta,
    longitudeDelta: lngDelta,
  };
}

/**
 * Determines whether a coordinate lies within the given visible MapRegion.
 */
export function isCoordinateInRegion(
  coord: MapCoordinates,
  region: MapRegion,
): boolean {
  const halfLat = region.latitudeDelta / 2;
  const halfLng = region.longitudeDelta / 2;

  return (
    coord.latitude >= region.latitude - halfLat &&
    coord.latitude <= region.latitude + halfLat &&
    coord.longitude >= region.longitude - halfLng &&
    coord.longitude <= region.longitude + halfLng
  );
}

/**
 * Randomly selects a crumb from the crumbs currently visible inside the viewport.
 * If none visible, selects from all available crumbs.
 */
export function pickRandomCraving(
  crumbs: EnrichedUserCrumb[],
  currentRegion?: MapRegion | null,
): EnrichedUserCrumb | null {
  const validCrumbs = crumbs.filter(
    (c) =>
      Number.isFinite(c.restaurant?.latitude) &&
      Number.isFinite(c.restaurant?.longitude),
  );

  if (validCrumbs.length === 0) {
    return null;
  }

  if (currentRegion) {
    const viewportCrumbs = validCrumbs.filter((c) =>
      isCoordinateInRegion(
        {
          latitude: c.restaurant.latitude!,
          longitude: c.restaurant.longitude!,
        },
        currentRegion,
      ),
    );

    if (viewportCrumbs.length > 0) {
      const randomIndex = Math.floor(Math.random() * viewportCrumbs.length);
      return viewportCrumbs[randomIndex];
    }
  }

  const randomIndex = Math.floor(Math.random() * validCrumbs.length);
  return validCrumbs[randomIndex];
}

/**
 * Calculates Mercator tile zoom level [0..20] from a MapRegion.
 */
export function regionToZoom(region: MapRegion): number {
  const lngDelta = Math.max(0.0001, region.longitudeDelta);
  return Math.max(0, Math.min(20, Math.floor(Math.log2(360 / lngDelta))));
}

/**
 * Pure spatial grid clustering algorithm.
 * Groups proximate crumbs together into clusters when zoomed out.
 */
export function getClusteredCrumbs(
  crumbs: EnrichedUserCrumb[],
  region: MapRegion,
): CrumbMapClusterItem[] {
  const validCrumbs = crumbs.filter(
    (c) =>
      Number.isFinite(c.restaurant?.latitude) &&
      Number.isFinite(c.restaurant?.longitude),
  );

  if (validCrumbs.length <= 1) {
    return validCrumbs.map((crumb) => ({
      type: 'Feature',
      properties: {
        cluster: false,
        crumb,
        crumbId: crumb.id,
      },
      geometry: {
        type: 'Point',
        coordinates: [crumb.restaurant.longitude!, crumb.restaurant.latitude!],
      },
    }));
  }

  // At close zoom (street level), show all individual markers
  if (region.longitudeDelta < 0.008) {
    return validCrumbs.map((crumb) => ({
      type: 'Feature',
      properties: {
        cluster: false,
        crumb,
        crumbId: crumb.id,
      },
      geometry: {
        type: 'Point',
        coordinates: [crumb.restaurant.longitude!, crumb.restaurant.latitude!],
      },
    }));
  }

  // Calculate dynamic grid size based on visible viewport deltas
  const cellSizeLng = Math.max(0.003, region.longitudeDelta / 7);
  const cellSizeLat = Math.max(0.003, region.latitudeDelta / 7);

  const gridMap = new Map<string, EnrichedUserCrumb[]>();

  for (const crumb of validCrumbs) {
    const lat = crumb.restaurant.latitude!;
    const lng = crumb.restaurant.longitude!;

    const cellX = Math.floor(lng / cellSizeLng);
    const cellY = Math.floor(lat / cellSizeLat);
    const key = `${cellX}:${cellY}`;

    const cellList = gridMap.get(key);
    if (cellList) {
      cellList.push(crumb);
    } else {
      gridMap.set(key, [crumb]);
    }
  }

  const results: CrumbMapClusterItem[] = [];

  for (const [key, cellCrumbs] of gridMap.entries()) {
    if (cellCrumbs.length === 1) {
      const crumb = cellCrumbs[0];
      results.push({
        type: 'Feature',
        properties: {
          cluster: false,
          crumb,
          crumbId: crumb.id,
        },
        geometry: {
          type: 'Point',
          coordinates: [
            crumb.restaurant.longitude!,
            crumb.restaurant.latitude!,
          ],
        },
      });
    } else {
      let sumLat = 0;
      let sumLng = 0;
      for (const c of cellCrumbs) {
        sumLat += c.restaurant.latitude!;
        sumLng += c.restaurant.longitude!;
      }

      const avgLat = sumLat / cellCrumbs.length;
      const avgLng = sumLng / cellCrumbs.length;

      results.push({
        type: 'Feature',
        properties: {
          cluster: true,
          cluster_id: `cluster-${key}`,
          point_count: cellCrumbs.length,
          crumbs: cellCrumbs,
        },
        geometry: {
          type: 'Point',
          coordinates: [avgLng, avgLat],
        },
      });
    }
  }

  return results;
}

/**
 * Computes an animated expansion region targeting all crumbs in a cluster.
 */
export function getClusterExpansionRegion(
  clusterCrumbs: EnrichedUserCrumb[],
): MapRegion {
  const coords: MapCoordinates[] = clusterCrumbs.map((c) => ({
    latitude: c.restaurant.latitude!,
    longitude: c.restaurant.longitude!,
  }));

  return getBoundingRegionForCoordinates(coords, 1.4);
}
